config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :users

  resources :users, only: [:update]

  # resources :topics do 
  #   resources :posts, except: [:index] do
  #     resources :comments, only: [:create, :destroy]
  #   end
  # end

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :topic

  default_scope { order('created_at DESC')}

  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    @comments = @post.comments
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated"
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error in saving the post. Please try again"
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post

    if @post.destroy
     flash[:notice] = "\"#{@post.title}\" was deleted successfully."
     redirect_to @topic
    else
     flash[:error] = "There was an error deleting the post."
     render :show
    end
  end

  private
  
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class= "alert alert-danger">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter post title" %>
  <% end %>

  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, row: 8, class: "form-control", placeholder: "Enter post body"%>
  <% end %>

    <% if post.image? %>
      <div class="form-group">
        <p>Current image</p>
         <%= image_tag( post.image.profile.url ) %>
      </div>
    <% end %>
    <div class="form-group">
       <%= f.label :image %>
       <%= f.file_field :image %>
       <%= f.hidden_field :image_cache %>
    </div>

    <div class="form-group">
      <%= f.submit "Save", class: "btn btn-success" %>
    </div>

<% end %>

app/views/posts/edit.html.erb
<h1> Edit the post </h1>

<div class="row">
  <div class = "col-md-4" >
    <p>Guidelines for posts</p>
    <ul>
       <li>Make sure the it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>

  <div class="col-md-8" >
    <%= render partial: 'form', locals: {topic: @topic, post: @post} %>
  </div>
</div>

app/views/posts/new.html.erb
<h1> This is a new post </h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: {topic: @topic, post: @post} %>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= markdown_to_html @post.title %></h1>

<div class = "row">
  <div class = "col-md-8">
    <small>
       <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
       submitted <%= time_ago_in_words(@post.created_at) %> ago by
       <%= @post.user.name %>
    </small>
    <p><%= markdown_to_html @post.body %></p>
  </div>
  <div class = "col-md-8">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post),class:"btn btn-success" %>
    <% end %>
    <% if policy(@post).destroy? %>
       <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
    <% end %>
  </div>
  <div class = "col-md-8">
    <p><strong> Comments </strong></p>
      <%= render partial: 'comments/comment', collection: @comments %>
  </div></br>
  <div class = "col-md-8">
    <%= render partial: 'comments/form', locals: {topic: @topic, post: @post, comment: @comments.new} %>
  </div>
</div>
  